### ISSUE TITLE
Styling: Side Menu

### ISSUE THREAD

**Issue by upluke** [chingu-voyages/v20-geckos-team-04#16]
includes size, background, click & hover effect etc.

**Comment by MobiusMan** [comment]
Is there any styling being used on the side menu currently?

**Comment by dev-tang** [comment]
yes in the App.css file

**Comment by MobiusMan** [comment]
Styling has been added/adjusted. I put up a screenshot in the Discord chat.

**Comment by dev-tang** [comment]
under review right now :)
