### ISSUE TITLE
Styling: Create Styling Guide Includes Fonts and Colors Schemes

### ISSUE THREAD

**Issue by upluke** [chingu-voyages/v20-geckos-team-04#19]

**Comment by MobiusMan** [comment]
I was thinking we could use Open Sans for all of the text if we wanted to. A heavy weight could be used for headers (like Bold 700), and a normal weight for text (like Regular 400).

https://fonts.google.com/specimen/Open+Sans?category=Sans+Serif

The color scheme is pretty simple right now. Most of the background is white. Light grey backgrounds use the Bootstrap class "bg-light." Dark grey elements use the "secondary" color class. The blue elements use the "primary" Bootstrap class.

https://getbootstrap.com/docs/4.5/utilities/colors/

Of course, we can spice it up pretty easily if we want to vary the color. Personally, I like the simplicity we have right now. It's very clean.

I will add this info to the "app.css" file if we are in agreement for the style scheme.

**Comment by upluke** [comment]
Great job!

**Comment by dev-tang** [comment]
looks good!
